networks:
  data_collection_network:
    external: true
    name: data_collection_network
    
services:
  # Kafka and connect Cluster setup
  zookeeper:
    image: bitnami/zookeeper:3.7.1
    ports:
      - "2181:2181"  # Zookeeper client port
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_4LW_COMMANDS_WHITELIST=ruok
    networks:
      - data_collection_network
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc zookeeper 2181 | grep imok"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1m

  kafka:
    image: bitnami/kafka:3.4.0
    ports:
      - "9093:9093" # External port for Kafka
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://kafka:9092, EXTERNAL://0.0.0.0:9093 # 내부용 : INERNAL, 외부용 : EXTERNAL
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://${BROKER_ID_1_IP_ADDRESS}:9093 
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=false
    networks:
      - data_collection_network
    depends_on:
      zookeeper:
        condition: service_healthy
    
  connect:
    image: confluentinc/cp-kafka-connect-base:7.4.0
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_GROUP_ID: connect-cluster
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
    volumes:
      - ./plugins:/usr/share/confluent-hub-components 
      - ./certs:/usr/share/elastic/config/certs
    networks:
      - data_collection_network
    depends_on:
      zookeeper:
        condition: service_healthy